### ISSUE TITLE
Cancelled order emails are not working

### ISSUE THREAD

**Issue by svaldesm** [godaddy-wordpress/woocommerce-expedited-order-email#2]
Hey @maxrice !
I know this is VERY old (like 6 years ago) but I found your post and it's very very interesting for what I'm trying to do.

I downloaded the plugin that you created for sending a cancelled email to the customer when the order gets cancelled (independent of the initial state). That's exactly what I need. 

I've been trying to make it work, but this lines are giving issues:

```
function register_woocommerce_cancelled_email_notification() {
	global $woocommerce;

	add_action( 'woocommerce_order_status_cancelled', array( $woocommerce, 'send_transactional_email') );
}

add_action( 'woocommerce_init', 'register_woocommerce_cancelled_email_notification' );
```

The error I get on WC debug is `class 'WooCommerce' does not have a method 'send_transactional_email'`

I've read there are other hooks to use, like `woocommerce_order_status_changed` but I don't want to use a filter for every order change, I think it will put too much load on something that is not generally the case. 

Is it possible to give a quick look to see what might be failing? I'm still searching for an answer but apparently this is too old, so probably everything on that code needs a revamp.

This is the link for the plugin: https://s9900.pcdn.co/wp-content/uploads/2014/02/woocommerce-cancelled-order-email.0.1.zip

Would really appreciate if you can take a quick look.

Thanks a lot for your time and congrats on the post, 6 years from now and still on the top of the searches!

**Comment by svaldesm** [comment]
From what I can see, the hook `woocommerce_order_status_cancelled` is still working.

**Comment by maxrice** [comment]
hey @svaldesm, glad to hear you found the post helpful. I've not updated this plugin in quite a while, so most of the code probably needs to be fixed to work with the latest version of WooCommerce. The error you mentioned appears to be because WC moved that `send_transactiona_email` function to the `WC_Emails` class, so you may be able to update that hook to use that class instead, see [here](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-emails.php).

If you want to create an order cancelled email without using custom code, I'd recommend giving [Jilt](https://jilt.com) a try — we built it for exactly this sort of thing, to make it really easy to send all kinds of emails for your WooCommerce store, including transactional emails. We [have a short guide](http://help.jilt.com/en/articles/2829131-creating-transactional-notifications) on setting up transactional notifications if you want to see how it would work.
